# Site settings
title: FUNS
email: 2459727330@qq.com
description: > # this means to ignore newlines until "baseurl:"
  My Blog
baseurl: "" # 网站目录
url: "http://funs.ml/" # 域名
# icon
icon-16x16: /assets/images/icon/favicon-16x16.ico
icon-32x32: /assets/images/icon/favicon-32x32.ico
# theme color
theme-color: { 
  default-color: cyan, 
  home-color: cyan,
  about-color: red,
  archive-color: pink,
  links-color: purple,
  tags-color: blue
} 
# mobile nav
mobile-hp: /assets/images/tx.png
mobile-bg: theme #若填写theme则使用theme-color的值。

# header 背景图片
header-bg: /assets/images/bg.png

# disqus
disqus-shortname: funs-ml

# cdn
cdn: false
cdnurl: https://jekyll-materialize.b0.upaiyun.com/

#google_analytics
google_analytics:

# 分享功能
# todd

#多个作者
defaultAuthor: admin
defaultAuthorImage: assets/images/tx.png
manyAuthors: true

# 是否使用gallery
gallery: false

# Build settings
#gems: [jekyll-sitemap]
markdown: kramdown

exclude: [vendor]
